name: LargeRaids
version: '${version}'
main: com.solarrabbit.largeraids.LargeRaids
api-version: 1.21
authors:
  - SolarRabbit

dependencies:
  server:
    PlaceholderAPI:
      required: false
    MythicMobs:
      required: false
    Multiverse-Core:
      required: false
